name = "hub"
main = ".svelte-kit/cloudflare/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = ".svelte-kit/cloudflare"

[env.production]
name = "hub"

[env.staging]  
name = "hub-staging"