name = "byte-incident-management"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = ".svelte-kit/cloudflare"

[env.production]
name = "byte-incident-management"

[env.staging]
name = "byte-incident-management-staging"