name = "byte-incident-management"
main = ".svelte-kit/output/server/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = ".svelte-kit/output/client"

[env.production]
name = "byte-incident-management"

[env.staging]
name = "byte-incident-management-staging"