name = "byte-incident-management"
main = ".svelte-kit/cloudflare/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "byte-incident-management"

[env.staging]
name = "byte-incident-management-staging"