name = "byte-incident-management"
main = ".svelte-kit/cloudflare-workers/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = ".svelte-kit/cloudflare-workers"

[env.production]
name = "byte-incident-management"

[env.staging]
name = "byte-incident-management-staging"